 //
// PROCESS CONTINUE OLARAK COIL AKTIF EDILDIGINDE 
// COIL DURUMUNU DEGISTIRMEK ICIN 	COIL_NO , COIL_OVER_WRITE ILE OR LARANARAK YAZILMALIDIR
//

#define   COIL_INT_COUNT										2

//#define COIL_PROCESS_CONTINUE		0x20

//-----------------------------------
#define RELAY_COUNT												64
#define RELAY_PROCESS_IN_PROGRESS								0x8000
#define RELAY_PROCESS_IN_BEGIN_PERIOD							0x4000
#define RELAY_PROCESS_BEGIN_PERIOD_DONE							0x2000
#define RELAY_PROCESS_NOT_IN_PROGRESS							0x1000

#define RELAY_PROCESS_MASK    									0xC0
	#define RELAY_PROCESS_ON    								0x80
	#define RELAY_PROCESS_OFF    								0x40
	#define RELAY_PROCESS_NONE									0x00
#define RELAY_BEGIN_PERIOD_PROCESS_MASK							0x30
	#define RELAY_BEGIN_PERIOD_PROCESS_ON   					0x20
	#define RELAY_BEGIN_PERIOD_PROCESS_OFF   					0x10
	#define RELAY_BEGIN_PERIOD_PROCESS_NONE						0x00
	
#define RELAY_PROCESS_OVER_WRITE								0x04
#define RELAY_PROCESS_CONTINUE									0x02

//
// PROCESS CONTINUE OLARAK COIL AKTIF EDILDIGINDE 
// COIL DURUMUNU DEGISTIRMEK ICIN 	COIL_NO , COIL_OVER_WRITE ILE OR LARANARAK YAZILMALIDIR
//

