//
//
// RELAY OUT 0
//
#define PLC_ONBOARD_DO_0_PORT			GPIOC
#define PLC_ONBOARD_DO_0_PIN			GPIO_PIN_9
//
// RELAY OUT 1
//
#define PLC_ONBOARD_DO_1_PORT			GPIOC
#define PLC_ONBOARD_DO_1_PIN			GPIO_PIN_8
//
// RELAY OUT 2
//
#define PLC_ONBOARD_DO_2_PORT			GPIOC
#define PLC_ONBOARD_DO_2_PIN			GPIO_PIN_7
//
// RELAY OUT 3
//
#define PLC_ONBOARD_DO_3_PORT			GPIOC
#define PLC_ONBOARD_DO_3_PIN			GPIO_PIN_6
//
// RELAY OUT 4
//
#define PLC_ONBOARD_DO_4_PORT			GPIOD
#define PLC_ONBOARD_DO_4_PIN			GPIO_PIN_15
//
// RELAY OUT 5
//
#define PLC_ONBOARD_DO_5_PORT			GPIOD
#define PLC_ONBOARD_DO_5_PIN			GPIO_PIN_14
//
// RELAY OUT 6
//
#define PLC_ONBOARD_DO_6_PORT			GPIOD
#define PLC_ONBOARD_DO_6_PIN			GPIO_PIN_13
//
// RELAY OUT 7
//
#define PLC_ONBOARD_DO_7_PORT			GPIOD
#define PLC_ONBOARD_DO_7_PIN			GPIO_PIN_12

//
// RELAY OUT 8
//
#define PLC_ONBOARD_DO_8_PORT			GPIOG
#define PLC_ONBOARD_DO_8_PIN			GPIO_PIN_1
//
// RELAY OUT 9
//
#define PLC_ONBOARD_DO_9_PORT			GPIOG
#define PLC_ONBOARD_DO_9_PIN			GPIO_PIN_0
//
// RELAY OUT 10
//
#define PLC_ONBOARD_DO_10_PORT			GPIOF
#define PLC_ONBOARD_DO_10_PIN			GPIO_PIN_15
//
// RELAY OUT 11
//
#define PLC_ONBOARD_DO_11_PORT			GPIOF
#define PLC_ONBOARD_DO_11_PIN			GPIO_PIN_14
//
// RELAY OUT 12
//
#define PLC_ONBOARD_DO_12_PORT			GPIOF
#define PLC_ONBOARD_DO_12_PIN			GPIO_PIN_13

//
// RELAY OUT 13
//
#define PLC_ONBOARD_DO_13_PORT			GPIOF
#define PLC_ONBOARD_DO_13_PIN			GPIO_PIN_2

//
// RELAY OUT 14
//
#define PLC_ONBOARD_DO_14_PORT			GPIOF
#define PLC_ONBOARD_DO_14_PIN			GPIO_PIN_1

//
// RELAY OUT 15
//
#define PLC_ONBOARD_DO_15_PORT			GPIOF
#define PLC_ONBOARD_DO_15_PIN			GPIO_PIN_0


void DigitalOutputWriteToMicroPort(unsigned short OutputData);
